#!/bin/bash

# current folder path
FOLDER_PATH="$(realpath $(dirname "${BASH_SOURCE[0]}"))"

# define an associative array
declare -A CONFIG_PATHS=(
    [local/bin]="${HOME}/.local/bin"
    [i3]="${HOME}/.config/i3"
    [i3status]="${HOME}/.config/i3status"
    [kitty]="${HOME}/.config/kitty"
    [tmux]="${HOME}/.config/tmux"
    [nvim]="${HOME}/.config/nvim"
    [volumeicon]="${HOME}/.config/volumeicon"
    [cust_prompt]="${HOME}/.custom_prompt"
    [alias]="${HOME}/.bash_aliases"
    [bashrc]="${HOME}/.bashrc"
    [xinit]="${HOME}/.xinitrc"
)

# ask and receive input from user
ask() {
    read -p "$1 (Y/n): " ans
    [ -z ans ] || [ "$ans" = "y" ]
}

# main code

# loops through associative array
for key in "${!CONFIG_PATHS[@]}"; do
    if ask "Do you want to link $key?"; then
        # if already exists it's moved to old and unlinked
        if [ -e "${CONFIG_PATHS[$key]}" ]; then
            mv "${CONFIG_PATHS[$key]}" "${CONFIG_PATHS[$key]}~"
            if [[ -L "${CONFIG_PATHS[$key]}~" ]]; then
                unlink "${CONFIG_PATHS[$key]}~"
            fi
        fi
        # sets target and links it
        target="${CONFIG_PATHS[$key]//$HOME/$FOLDER_PATH}"
        ln -s "$target" "${CONFIG_PATHS[$key]}" 
    fi
done

echo "Done! :)"
exit 0
